"""
Simple script to check Firestore data structure
This will help diagnose why subcategories aren't showing
"""

print("=" * 70)
print("FIRESTORE DATA VERIFICATION CHECKLIST")
print("=" * 70)
print()
print("Please manually verify the following in Firebase Console:")
print("https://console.firebase.google.com/project/rps-statationary-jaipu/firestore")
print()

print("1️⃣  SUBCATEGORIES COLLECTION (/subcategories)")
print("-" * 70)
print("   ✓ Check if collection exists")
print("   ✓ Count total documents")
print("   ✓ Check if any have 'isActive: true' or 'is_active: true'")
print("   ✓ Verify each document has:")
print("      - name (string)")
print("      - categoryId or category_id (string)")
print("      - image (string URL)")
print("      - isActive or is_active (boolean)")
print("      - rank (number)")
print()

print("2️⃣  HOME SECTIONS COLLECTION (/home_sections)")
print("-" * 70)
print("   ✓ Check if collection exists")
print("   ✓ Count total documents")
print("   ✓ Check if any have 'isLive: true' or 'is_live: true'")
print("   ✓ Verify each document has:")
print("      - title (string)")
print("      - isLive or is_live (boolean)")
print("      - rank (number)")
print()

print("3️⃣  HOME SECTION ITEMS (/home_sections/{sectionId}/items)")
print("-" * 70)
print("   ✓ Pick any section document ID")
print("   ✓ Go to its 'items' subcollection")
print("   ✓ Verify EACH item has:")
print("      - name (string)")
print("      - productId or product_id (string)")
print("      - skuId or sku_id (string)")
print("      - ⚠️  categoryId or category_id (string) - REQUIRED!")
print("      - ⚠️  subcategoryId or subcategory_id (string) - REQUIRED!")
print("      - price (number)")
print("      - imageUrl or image_url (string)")
print()

print("4️⃣  COMMON ISSUES")
print("-" * 70)
print("   Issue: Only 'All' shows in subcategory filter")
print("   → No subcategories exist OR all have isActive: false")
print()
print("   Issue: Products not showing")
print("   → Items missing categoryId/subcategoryId fields")
print()
print("   Issue: Filtering doesn't work")
print("   → Field name mismatch (check if using snake_case or camelCase)")
print()

print("5️⃣  QUICK FIX - Add Sample Subcategory")
print("-" * 70)
print("   If no subcategories exist, add one manually:")
print("   Collection: subcategories")
print("   Document ID: (auto-generate)")
print("   Fields:")
print("   {")
print('     "name": "Notebooks",')
print('     "category_id": "your_category_id",')
print('     "image": "https://example.com/notebook.jpg",')
print('     "is_active": true,')
print('     "rank": 1')
print("   }")
print()

print("6️⃣  QUICK FIX - Update Home Section Items")
print("-" * 70)
print("   For each item in /home_sections/{sectionId}/items:")
print("   Add these fields if missing:")
print("   {")
print('     "category_id": "actual_category_id",')
print('     "subcategory_id": "actual_subcategory_id"')
print("   }")
print()

print("=" * 70)
print("After verifying/fixing, restart the Flutter app to see changes")
print("=" * 70)
