// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAv8g6j-JEpVRL6sPTUsQjZSlDZ5RSmes',
    appId: '1:1090273726787:android:5b0827e6ec755af8701ff6',
    messagingSenderId: '1090273726787',
    projectId: 'rps-statationary-jaipur',
    databaseURL: 'https://rps-statationary-jaipur-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rps-statationary-jaipur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFY4riwGzbtsD_cCBK9Q9nJQzfHvGCBZM',
    appId: '1:1090273726787:ios:a33b579527d4d6bd701ff6',
    messagingSenderId: '1090273726787',
    projectId: 'rps-statationary-jaipur',
    databaseURL: 'https://rps-statationary-jaipur-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rps-statationary-jaipur.firebasestorage.app',
    androidClientId: '1090273726787-7med1jcpttfhn58e3s6evd4lrcbu5fph.apps.googleusercontent.com',
    iosClientId: '1090273726787-8fcbjdhc14lj0hsdu9e65amrfod6v9it.apps.googleusercontent.com',
    iosBundleId: 'com.devay.rpsStationery',
  );

}
